name: Daily price check

on:
  schedule:
    - cron: '0 0 * * *' # JST 09:00
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level'
        required: true
        default: 'INFO'
        type: choice
        options:
          - DEBUG
          - INFO
          - WARNING
          - ERROR
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: ${{ github.event.inputs.log_level }}
      ITEM_PAGE_URLS: ${{ vars.ITEM_PAGE_URLS }}
      NOTIFY_WEBHOOK_URL: ${{ secrets.NOTIFY_WEBHOOK_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r src/anatae/requirements.txt

      - name: Install Playwright browsers
        run: playwright install

      - name: Run Python script
        run: python -m src.anatae.price_check
